version: '3.9'
services:
  frontend: # The name of the service
    container_name: angularcontainer  # Container name
    build: .
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true

